### ISSUE TITLE
Atom name and abundance doesn't update when a neutron is grabbed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#38]
In 1.0.0-dev.5, the name or abundance of an atom doesn't change when a neutron is grabbed out of the nucleus until the neutron is released. The symbol DOES update. @amyh-phet this behaviour does not match the Java and in my opinion is counter intuitive. The nucleus seen not matching the nucleus reported would cause confusion:

![isoatma2](https://cloud.githubusercontent.com/assets/5863899/12623437/6ceeb5ec-c4e7-11e5-847c-282b8ffa4c0c.gif)

This video starts with Hydrogen-5, and I take one neutron out a time. When I grab the neutron, the nucleus only shows a mass of 4, but the name displayed is still Hydrogen-5. The symbol and scale correctly show a mass of 4.

phetsims/tasks/issues/488

**Comment by phet-steele** [comment]
@aadish  In the Java version of the sim, the name of the isotope updates when one of the two behaviors occurs:
1) a neutron that is in the nucleus is selected 
2) a neutron from the bucket is dragged into the nucleus and released.

Can we investigate matching the behavior of the Java sim for neutrons on the Make Isotopes screen?

**Comment by aadish** [comment]
fixed, closing

**Comment by phet-steele** [comment]
@aadish this is actually not fixed. The above commit does not take into account when you grab the LAST neutron in an atom. My guess is that

`self.particleAtom.neutronCount > 0`

should be changed to 

`self.particleAtom.neutronCount >= 0`

@ariel-phet said:
"if possible this would be good to fix as a maintenance release so long as the [actual] fix is not too invasive"

**Comment by aadish** [comment]
@phet-steele thanks for catching this and yes the fix is the one suggested by you, it should have been fixed by the above commit, will go ahead and create a maintenance release

**Comment by phet-steele** [comment]
Looks good, thanks @aadish.
